--- #YAML:1.0
name:               PAR-Repository
version:            0.17
abstract:           Create and modify PAR repositories
author:
    - Steffen Müller <smueller@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Zip:         0
    DBM::Deep:            1.0012
    Digest::MD5:          0
    ExtUtils::Manifest:   0
    File::Copy:           0
    File::Path:           0
    File::Spec:           0
    File::Temp:           0
    PAR::Dist:            0.31
    PAR::Indexer:         0.90
    PAR::Repository::Query:  0.12
    Pod::Text:            0
    version:              0.50
    YAML::Syck:           0.62
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
